name: Build and Test

on:
  [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: ./build.sh

    - name: Test
      run: ./test.sh
